version: 2
jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          context: 'EBS Deploy'
          filters:
            branches:
              only:
                - master
